name: new_project
description: new Sacle Flutter App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  logger: ^1.1.0
  retrofit: '>=3.0.0 <4.0.0'
  freezed: ^2.0.3+1
  dio: ^4.0.6
  get_it: ^7.2.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  freezed_annotation: ^2.0.3
  fluttertoast: ^8.0.9
  flutter_riverpod: ^1.0.4


dev_dependencies:
  retrofit_generator: '>=4.0.0 <5.0.0'
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
